# Cloudflare Pages 配置
name = "rolitt"
compatibility_date = "2024-12-19"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".open-next"

# 环境变量配置
[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://rolitt.com"
NEXT_PUBLIC_GA_ID = "G-XXXXXXXXXX"
NEXT_PUBLIC_META_PIXEL_ID = "XXXXXXXXXX"
NEXT_PUBLIC_MICROSOFT_CLARITY_ID = "XXXXXXXXXX"
NEXT_PUBLIC_TIKTOK_PIXEL_ID = "XXXXXXXXXX"
NEXT_PUBLIC_KLAVIYO_ID = "XXXXXXXXXX"
NEXT_PUBLIC_FIREBASE_API_KEY = "XXXXXXXXXX"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "rolitt-official.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "rolitt-official"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "rolitt-official.appspot.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "XXXXXXXXXX"
NEXT_PUBLIC_FIREBASE_APP_ID = "XXXXXXXXXX"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_XXXXXXXXXX"
NEXT_PUBLIC_POSTHOG_KEY = "XXXXXXXXXX"
NEXT_PUBLIC_POSTHOG_HOST = "https://us.i.posthog.com"

[env.preview]

[env.preview.vars]
CACHE_CONTROL = "public, max-age=3600"
