/**
 * PDF 报告生成器
 * 使用 Puppeteer 生成高质量的手相分析PDF报告
 */

import puppeteer from 'puppeteer';

export interface PalmReportData {
  title: string;
  subtitle: string;
  session: {
    id: string;
    type: string;
    handType: string;
    createdAt: string;
  };
  content: {
    personality?: {
      traits: string[];
      strengths: string[];
      challenges: string[];
      summary: string;
    };
    health?: {
      vitality: number;
      areas: string[];
      recommendations: string[];
      summary: string;
    };
    career?: {
      aptitudes: string[];
      opportunities: string[];
      challenges: string[];
      summary: string;
    };
    relationship?: {
      compatibility: string[];
      communication: string[];
      challenges: string[];
      summary: string;
    };
    fortune?: {
      financial: string[];
      opportunities: string[];
      timing: string[];
      summary: string;
    };
  };
  language: string;
  metadata: {
    generatedAt: Date;
    version: string;
    userId: string;
  };
}

/**
 * 生成手相分析PDF报告
 */
export async function generatePalmPDFReport(data: PalmReportData): Promise<Buffer> {
  let browser: puppeteer.Browser | null = null;

  try {
    // 启动浏览器
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process',
        '--disable-gpu'
      ]
    });

    const page = await browser.newPage();

    // 设置页面格式
    await page.setViewport({ width: 1200, height: 1600 });

    // 生成HTML内容
    const htmlContent = generateReportHTML(data);

    // 设置HTML内容
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    // 生成PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm'
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; text-align: center; margin-top: 10px;">
          <span>${data.title} - ${data.session.type}</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; text-align: center; display: flex; justify-content: space-between; padding: 0 15mm;">
          <span>Generated by Palm AI - Powered by Rolitt</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `
    });

    return pdfBuffer;

  } catch (error) {
    console.error('PDF generation failed:', error);
    throw new Error(`PDF生成失败: ${error instanceof Error ? error.message : '未知错误'}`);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

/**
 * 生成报告HTML内容
 */
function generateReportHTML(data: PalmReportData): string {
  const { content } = data;
  
  return `
    <!DOCTYPE html>
    <html lang="${data.language}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${data.title}</title>
        <style>
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }
            
            body {
                font-family: 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
            }
            
            .container {
                max-width: 800px;
                margin: 0 auto;
                background: white;
                min-height: 100vh;
                box-shadow: 0 0 20px rgba(0,0,0,0.1);
            }
            
            .header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 40px 30px;
                text-align: center;
                position: relative;
                overflow: hidden;
            }
            
            .header::before {
                content: '';
                position: absolute;
                top: -50%;
                left: -50%;
                width: 200%;
                height: 200%;
                background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><pattern id="palm" patternUnits="userSpaceOnUse" width="20" height="20"><circle cx="10" cy="10" r="2" fill="rgba(255,255,255,0.1)"/></pattern></defs><rect width="100" height="100" fill="url(%23palm)"/></svg>') repeat;
                animation: float 20s ease-in-out infinite;
            }
            
            @keyframes float {
                0%, 100% { transform: translateY(0px); }
                50% { transform: translateY(-10px); }
            }
            
            .header h1 {
                font-size: 2.5em;
                font-weight: 300;
                margin-bottom: 10px;
                position: relative;
                z-index: 1;
            }
            
            .header .subtitle {
                font-size: 1.1em;
                opacity: 0.9;
                position: relative;
                z-index: 1;
            }
            
            .session-info {
                background: #f8f9fa;
                padding: 20px 30px;
                border-bottom: 3px solid #667eea;
            }
            
            .session-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 15px;
            }
            
            .session-item {
                display: flex;
                align-items: center;
                gap: 10px;
            }
            
            .session-label {
                font-weight: 600;
                color: #667eea;
                min-width: 80px;
            }
            
            .content {
                padding: 30px;
            }
            
            .section {
                margin-bottom: 40px;
                break-inside: avoid;
            }
            
            .section-title {
                font-size: 1.8em;
                font-weight: 600;
                color: #667eea;
                margin-bottom: 20px;
                padding-bottom: 10px;
                border-bottom: 2px solid #667eea;
                display: flex;
                align-items: center;
                gap: 10px;
            }
            
            .section-icon {
                width: 30px;
                height: 30px;
                border-radius: 50%;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
                font-size: 1.2em;
            }
            
            .summary-box {
                background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
                padding: 20px;
                border-radius: 10px;
                margin-bottom: 20px;
                border-left: 4px solid #667eea;
            }
            
            .summary-text {
                font-style: italic;
                font-size: 1.1em;
                line-height: 1.8;
                color: #555;
            }
            
            .traits-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 20px;
                margin-top: 20px;
            }
            
            .trait-category {
                background: white;
                border: 1px solid #e9ecef;
                border-radius: 10px;
                padding: 20px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.05);
            }
            
            .trait-category h4 {
                font-size: 1.2em;
                margin-bottom: 15px;
                color: #667eea;
                display: flex;
                align-items: center;
                gap: 8px;
            }
            
            .trait-list {
                list-style: none;
            }
            
            .trait-list li {
                padding: 8px 0;
                border-bottom: 1px solid #f1f3f4;
                position: relative;
                padding-left: 20px;
            }
            
            .trait-list li:last-child {
                border-bottom: none;
            }
            
            .trait-list li::before {
                content: '●';
                color: #667eea;
                position: absolute;
                left: 0;
                top: 8px;
            }
            
            .vitality-score {
                text-align: center;
                margin: 20px 0;
            }
            
            .vitality-number {
                font-size: 3em;
                font-weight: bold;
                color: #667eea;
                display: block;
            }
            
            .vitality-label {
                font-size: 1.1em;
                color: #666;
                margin-top: 5px;
            }
            
            .progress-bar {
                width: 100%;
                height: 20px;
                background: #e9ecef;
                border-radius: 10px;
                overflow: hidden;
                margin: 10px 0;
            }
            
            .progress-fill {
                height: 100%;
                background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
                border-radius: 10px;
                transition: width 0.3s ease;
            }
            
            .footer {
                background: #f8f9fa;
                padding: 30px;
                text-align: center;
                border-top: 1px solid #e9ecef;
                margin-top: 40px;
            }
            
            .footer-text {
                color: #666;
                font-size: 0.9em;
                line-height: 1.6;
            }
            
            .disclaimer {
                background: #fff3cd;
                border: 1px solid #ffeaa7;
                border-radius: 10px;
                padding: 20px;
                margin: 30px 0;
            }
            
            .disclaimer-title {
                font-weight: 600;
                color: #856404;
                margin-bottom: 10px;
            }
            
            .disclaimer-text {
                color: #856404;
                font-size: 0.9em;
                line-height: 1.6;
            }
            
            @page {
                margin: 0;
            }
            
            @media print {
                body {
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
            }
        </style>
    </head>
    <body>
        <div class="container">
            <!-- 头部 -->
            <div class="header">
                <h1>🖐️ ${data.title}</h1>
                <div class="subtitle">${data.subtitle}</div>
            </div>
            
            <!-- 会话信息 -->
            <div class="session-info">
                <div class="session-grid">
                    <div class="session-item">
                        <span class="session-label">会话ID:</span>
                        <span>${data.session.id}</span>
                    </div>
                    <div class="session-item">
                        <span class="session-label">分析类型:</span>
                        <span>${data.session.type}</span>
                    </div>
                    <div class="session-item">
                        <span class="session-label">手型:</span>
                        <span>${data.session.handType}</span>
                    </div>
                    <div class="session-item">
                        <span class="session-label">生成时间:</span>
                        <span>${data.session.createdAt}</span>
                    </div>
                </div>
            </div>
            
            <!-- 主要内容 -->
            <div class="content">
                ${generateSectionHTML('🧠', '个性分析', content.personality)}
                ${generateSectionHTML('💚', '健康分析', content.health)}
                ${generateSectionHTML('💼', '事业洞察', content.career)}
                ${generateSectionHTML('❤️', '感情分析', content.relationship)}
                ${generateSectionHTML('🍀', '财运分析', content.fortune)}
                
                <!-- 免责声明 -->
                <div class="disclaimer">
                    <div class="disclaimer-title">⚠️ 重要声明</div>
                    <div class="disclaimer-text">
                        本报告仅供娱乐参考，不应作为人生决策的依据。手相分析是一门传统艺术，
                        结果可能因个人解读而异。请理性对待分析结果，重要决策建议咨询专业人士。
                    </div>
                </div>
            </div>
            
            <!-- 页脚 -->
            <div class="footer">
                <div class="footer-text">
                    <strong>Palm AI - 人工智能手相分析</strong><br>
                    Powered by Rolitt | 生成时间: ${data.metadata.generatedAt.toLocaleString()}<br>
                    版本: ${data.metadata.version} | 语言: ${data.language.toUpperCase()}
                </div>
            </div>
        </div>
    </body>
    </html>
  `;
}

/**
 * 生成各个分析部分的HTML
 */
function generateSectionHTML(icon: string, title: string, data: any): string {
  if (!data) return '';

  let contentHTML = '';

  // 生成摘要
  if (data.summary) {
    contentHTML += `
      <div class="summary-box">
        <div class="summary-text">${data.summary}</div>
      </div>
    `;
  }

  // 根据不同类型生成内容
  if (title === '健康分析' && data.vitality !== undefined) {
    contentHTML += `
      <div class="vitality-score">
        <span class="vitality-number">${data.vitality}</span>
        <div class="vitality-label">活力指数 / 100</div>
        <div class="progress-bar">
          <div class="progress-fill" style="width: ${data.vitality}%"></div>
        </div>
      </div>
    `;
  }

  // 生成特征列表
  const categories = [];
  
  if (data.traits) categories.push({ title: '✨ 主要特质', items: data.traits });
  if (data.strengths) categories.push({ title: '💪 优势特征', items: data.strengths });
  if (data.challenges) categories.push({ title: '🎯 成长空间', items: data.challenges });
  if (data.areas) categories.push({ title: '🔍 关注领域', items: data.areas });
  if (data.recommendations) categories.push({ title: '💡 建议', items: data.recommendations });
  if (data.aptitudes) categories.push({ title: '🌟 天赋才能', items: data.aptitudes });
  if (data.opportunities) categories.push({ title: '🚀 发展机遇', items: data.opportunities });
  if (data.compatibility) categories.push({ title: '💕 兼容特质', items: data.compatibility });
  if (data.communication) categories.push({ title: '🗣️ 沟通方式', items: data.communication });
  if (data.financial) categories.push({ title: '💰 财务状况', items: data.financial });
  if (data.timing) categories.push({ title: '⏰ 最佳时机', items: data.timing });

  if (categories.length > 0) {
    contentHTML += '<div class="traits-grid">';
    categories.forEach(category => {
      contentHTML += `
        <div class="trait-category">
          <h4>${category.title}</h4>
          <ul class="trait-list">
            ${category.items.map((item: string) => `<li>${item}</li>`).join('')}
          </ul>
        </div>
      `;
    });
    contentHTML += '</div>';
  }

  return `
    <div class="section">
      <div class="section-title">
        <div class="section-icon">${icon}</div>
        ${title}
      </div>
      ${contentHTML}
    </div>
  `;
}