name: Railway Auto Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy to Railway
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to Railway
        uses: railway-app/railway-deploy@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: ${{ secrets.RAILWAY_SERVICE_ID }}
